/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./../src/context"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
  PaymentStatus: "COMPLETED" | "PENDING" | "SKIPPED"
  PayrollRunStatus: "COMPLETED" | "IN_PROGRESS" | "PENDING"
  SalaryCurrency: "USD" | "ZEC"
  Schedule: "EVERY_MONTH" | "EVERY_TWO_WEEKS" | "EVERY_X_DAYS"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  AuthPayload: { // root type
    token: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  DashboardStats: { // root type
    nextPayrollDue?: NexusGenRootTypes['NextPayrollDue'] | null; // NextPayrollDue
    recentRuns: NexusGenRootTypes['PayrollRun'][]; // [PayrollRun!]!
    zecSpentByMonth: NexusGenRootTypes['ZecSpentByMonth'][]; // [ZecSpentByMonth!]!
  }
  DelegateInvite: { // root type
    id: string; // ID!
  }
  DelegateInvitePreview: { // root type
    expiresAt: string; // String!
    ownerUsername: string; // String!
  }
  Employee: { // root type
    id: string; // ID!
    name: string; // String!
    salaryAmount: number; // Float!
    salaryCurrency: NexusGenEnums['SalaryCurrency']; // SalaryCurrency!
    title?: string | null; // String
    walletAddress: string; // String!
    walletVerified: boolean; // Boolean!
  }
  Mutation: {};
  NextPayrollDue: { // root type
    dueDate: string; // String!
    employeeCount: number; // Int!
    id: string; // ID!
    name: string; // String!
    totalUsd: number; // Float!
  }
  Payment: { // root type
    amountUsd: number; // Float!
    amountZec: number; // Float!
    id: string; // ID!
    memo: string; // String!
    status: NexusGenEnums['PaymentStatus']; // PaymentStatus!
    txHash?: string | null; // String
  }
  Payroll: { // root type
    customDays?: number | null; // Int
    id: string; // ID!
    name: string; // String!
    schedule: NexusGenEnums['Schedule']; // Schedule!
  }
  PayrollEmployee: { // root type
    employeeId: string; // String!
    payrollId: string; // String!
  }
  PayrollRun: { // root type
    id: string; // ID!
    zecPriceUsd: number; // Float!
  }
  Query: {};
  User: { // root type
    id: string; // ID!
    name?: string | null; // String
    username: string; // String!
    walletBirthdayHeight?: number | null; // Int
  }
  ZecBalance: { // root type
    available: number; // Float!
  }
  ZecSpentByMonth: { // root type
    amount: number; // Float!
    month: string; // String!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  AuthPayload: { // field return type
    token: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  DashboardStats: { // field return type
    nextPayrollDue: NexusGenRootTypes['NextPayrollDue'] | null; // NextPayrollDue
    recentRuns: NexusGenRootTypes['PayrollRun'][]; // [PayrollRun!]!
    zecSpentByMonth: NexusGenRootTypes['ZecSpentByMonth'][]; // [ZecSpentByMonth!]!
  }
  DelegateInvite: { // field return type
    createdAt: string; // String!
    expiresAt: string; // String!
    id: string; // ID!
    token: string; // String!
  }
  DelegateInvitePreview: { // field return type
    expiresAt: string; // String!
    ownerUsername: string; // String!
  }
  Employee: { // field return type
    createdAt: string; // String!
    id: string; // ID!
    name: string; // String!
    salaryAmount: number; // Float!
    salaryCurrency: NexusGenEnums['SalaryCurrency']; // SalaryCurrency!
    title: string | null; // String
    updatedAt: string; // String!
    walletAddress: string; // String!
    walletVerified: boolean; // Boolean!
  }
  Mutation: { // field return type
    acceptDelegateInvite: NexusGenRootTypes['AuthPayload']; // AuthPayload!
    changePassword: NexusGenRootTypes['AuthPayload']; // AuthPayload!
    completePayrollRun: NexusGenRootTypes['PayrollRun']; // PayrollRun!
    createDelegateInvite: NexusGenRootTypes['DelegateInvite']; // DelegateInvite!
    createEmployee: NexusGenRootTypes['Employee']; // Employee!
    createPayroll: NexusGenRootTypes['Payroll']; // Payroll!
    deleteAccount: boolean; // Boolean!
    deleteEmployee: NexusGenRootTypes['Employee']; // Employee!
    deletePayroll: NexusGenRootTypes['Payroll']; // Payroll!
    importEmployeesCsv: NexusGenRootTypes['Employee'][]; // [Employee!]!
    login: NexusGenRootTypes['AuthPayload']; // AuthPayload!
    register: NexusGenRootTypes['AuthPayload']; // AuthPayload!
    removeDelegate: NexusGenRootTypes['User']; // User!
    revokeDelegateInvite: NexusGenRootTypes['DelegateInvite']; // DelegateInvite!
    startPayrollRun: NexusGenRootTypes['PayrollRun']; // PayrollRun!
    updateEmployee: NexusGenRootTypes['Employee']; // Employee!
    updatePaymentStatus: NexusGenRootTypes['Payment']; // Payment!
    updatePayroll: NexusGenRootTypes['Payroll']; // Payroll!
    updateUser: NexusGenRootTypes['User']; // User!
  }
  NextPayrollDue: { // field return type
    dueDate: string; // String!
    employeeCount: number; // Int!
    id: string; // ID!
    name: string; // String!
    totalUsd: number; // Float!
  }
  Payment: { // field return type
    amountUsd: number; // Float!
    amountZec: number; // Float!
    createdAt: string; // String!
    employee: NexusGenRootTypes['Employee']; // Employee!
    id: string; // ID!
    memo: string; // String!
    payroll: NexusGenRootTypes['Payroll']; // Payroll!
    status: NexusGenEnums['PaymentStatus']; // PaymentStatus!
    txHash: string | null; // String
  }
  Payroll: { // field return type
    createdAt: string; // String!
    customDays: number | null; // Int
    employees: NexusGenRootTypes['PayrollEmployee'][]; // [PayrollEmployee!]!
    id: string; // ID!
    name: string; // String!
    runs: NexusGenRootTypes['PayrollRun'][]; // [PayrollRun!]!
    schedule: NexusGenEnums['Schedule']; // Schedule!
  }
  PayrollEmployee: { // field return type
    employee: NexusGenRootTypes['Employee']; // Employee!
    employeeId: string; // String!
    payrollId: string; // String!
  }
  PayrollRun: { // field return type
    completedAt: string | null; // String
    createdAt: string; // String!
    id: string; // ID!
    payments: NexusGenRootTypes['Payment'][]; // [Payment!]!
    payroll: NexusGenRootTypes['Payroll']; // Payroll!
    status: NexusGenEnums['PayrollRunStatus']; // PayrollRunStatus!
    zecPriceUsd: number; // Float!
  }
  Query: { // field return type
    dashboardStats: NexusGenRootTypes['DashboardStats']; // DashboardStats!
    delegateInvite: NexusGenRootTypes['DelegateInvitePreview'] | null; // DelegateInvitePreview
    delegateInvites: NexusGenRootTypes['DelegateInvite'][]; // [DelegateInvite!]!
    delegates: NexusGenRootTypes['User'][]; // [User!]!
    employee: NexusGenRootTypes['Employee'] | null; // Employee
    employees: NexusGenRootTypes['Employee'][]; // [Employee!]!
    me: NexusGenRootTypes['User'] | null; // User
    payments: NexusGenRootTypes['Payment'][]; // [Payment!]!
    payroll: NexusGenRootTypes['Payroll'] | null; // Payroll
    payrollRun: NexusGenRootTypes['PayrollRun'] | null; // PayrollRun
    payrolls: NexusGenRootTypes['Payroll'][]; // [Payroll!]!
    zecBalance: NexusGenRootTypes['ZecBalance'] | null; // ZecBalance
  }
  User: { // field return type
    createdAt: string; // String!
    employees: NexusGenRootTypes['Employee'][]; // [Employee!]!
    hasEmployees: boolean; // Boolean!
    hasPayrollRun: boolean; // Boolean!
    hasPayrolls: boolean; // Boolean!
    hasVerifiedPayment: boolean; // Boolean!
    hasWallet: boolean; // Boolean!
    id: string; // ID!
    name: string | null; // String
    needsWalkthrough: boolean; // Boolean!
    owner: NexusGenRootTypes['User'] | null; // User
    payrolls: NexusGenRootTypes['Payroll'][]; // [Payroll!]!
    username: string; // String!
    walletBirthdayHeight: number | null; // Int
    zcashViewingKey: string | null; // String
  }
  ZecBalance: { // field return type
    available: number; // Float!
  }
  ZecSpentByMonth: { // field return type
    amount: number; // Float!
    month: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  AuthPayload: { // field return type name
    token: 'String'
    user: 'User'
  }
  DashboardStats: { // field return type name
    nextPayrollDue: 'NextPayrollDue'
    recentRuns: 'PayrollRun'
    zecSpentByMonth: 'ZecSpentByMonth'
  }
  DelegateInvite: { // field return type name
    createdAt: 'String'
    expiresAt: 'String'
    id: 'ID'
    token: 'String'
  }
  DelegateInvitePreview: { // field return type name
    expiresAt: 'String'
    ownerUsername: 'String'
  }
  Employee: { // field return type name
    createdAt: 'String'
    id: 'ID'
    name: 'String'
    salaryAmount: 'Float'
    salaryCurrency: 'SalaryCurrency'
    title: 'String'
    updatedAt: 'String'
    walletAddress: 'String'
    walletVerified: 'Boolean'
  }
  Mutation: { // field return type name
    acceptDelegateInvite: 'AuthPayload'
    changePassword: 'AuthPayload'
    completePayrollRun: 'PayrollRun'
    createDelegateInvite: 'DelegateInvite'
    createEmployee: 'Employee'
    createPayroll: 'Payroll'
    deleteAccount: 'Boolean'
    deleteEmployee: 'Employee'
    deletePayroll: 'Payroll'
    importEmployeesCsv: 'Employee'
    login: 'AuthPayload'
    register: 'AuthPayload'
    removeDelegate: 'User'
    revokeDelegateInvite: 'DelegateInvite'
    startPayrollRun: 'PayrollRun'
    updateEmployee: 'Employee'
    updatePaymentStatus: 'Payment'
    updatePayroll: 'Payroll'
    updateUser: 'User'
  }
  NextPayrollDue: { // field return type name
    dueDate: 'String'
    employeeCount: 'Int'
    id: 'ID'
    name: 'String'
    totalUsd: 'Float'
  }
  Payment: { // field return type name
    amountUsd: 'Float'
    amountZec: 'Float'
    createdAt: 'String'
    employee: 'Employee'
    id: 'ID'
    memo: 'String'
    payroll: 'Payroll'
    status: 'PaymentStatus'
    txHash: 'String'
  }
  Payroll: { // field return type name
    createdAt: 'String'
    customDays: 'Int'
    employees: 'PayrollEmployee'
    id: 'ID'
    name: 'String'
    runs: 'PayrollRun'
    schedule: 'Schedule'
  }
  PayrollEmployee: { // field return type name
    employee: 'Employee'
    employeeId: 'String'
    payrollId: 'String'
  }
  PayrollRun: { // field return type name
    completedAt: 'String'
    createdAt: 'String'
    id: 'ID'
    payments: 'Payment'
    payroll: 'Payroll'
    status: 'PayrollRunStatus'
    zecPriceUsd: 'Float'
  }
  Query: { // field return type name
    dashboardStats: 'DashboardStats'
    delegateInvite: 'DelegateInvitePreview'
    delegateInvites: 'DelegateInvite'
    delegates: 'User'
    employee: 'Employee'
    employees: 'Employee'
    me: 'User'
    payments: 'Payment'
    payroll: 'Payroll'
    payrollRun: 'PayrollRun'
    payrolls: 'Payroll'
    zecBalance: 'ZecBalance'
  }
  User: { // field return type name
    createdAt: 'String'
    employees: 'Employee'
    hasEmployees: 'Boolean'
    hasPayrollRun: 'Boolean'
    hasPayrolls: 'Boolean'
    hasVerifiedPayment: 'Boolean'
    hasWallet: 'Boolean'
    id: 'ID'
    name: 'String'
    needsWalkthrough: 'Boolean'
    owner: 'User'
    payrolls: 'Payroll'
    username: 'String'
    walletBirthdayHeight: 'Int'
    zcashViewingKey: 'String'
  }
  ZecBalance: { // field return type name
    available: 'Float'
  }
  ZecSpentByMonth: { // field return type name
    amount: 'Float'
    month: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    acceptDelegateInvite: { // args
      name: string; // String!
      password: string; // String!
      token: string; // String!
      username: string; // String!
    }
    changePassword: { // args
      currentPassword: string; // String!
      newPassword: string; // String!
    }
    completePayrollRun: { // args
      runId: string; // ID!
    }
    createEmployee: { // args
      name: string; // String!
      salaryAmount: number; // Float!
      salaryCurrency?: NexusGenEnums['SalaryCurrency'] | null; // SalaryCurrency
      title?: string | null; // String
      walletAddress: string; // String!
    }
    createPayroll: { // args
      customDays?: number | null; // Int
      employeeIds: string[]; // [ID!]!
      name: string; // String!
      schedule: NexusGenEnums['Schedule']; // Schedule!
    }
    deleteEmployee: { // args
      id: string; // ID!
    }
    deletePayroll: { // args
      id: string; // ID!
    }
    importEmployeesCsv: { // args
      csvContent: string; // String!
    }
    login: { // args
      password: string; // String!
      username: string; // String!
    }
    register: { // args
      password: string; // String!
      username: string; // String!
    }
    removeDelegate: { // args
      id: string; // ID!
    }
    revokeDelegateInvite: { // args
      id: string; // ID!
    }
    startPayrollRun: { // args
      payrollId: string; // ID!
    }
    updateEmployee: { // args
      id: string; // ID!
      name?: string | null; // String
      salaryAmount?: number | null; // Float
      salaryCurrency?: NexusGenEnums['SalaryCurrency'] | null; // SalaryCurrency
      title?: string | null; // String
      walletAddress?: string | null; // String
    }
    updatePaymentStatus: { // args
      paymentId: string; // ID!
      status: NexusGenEnums['PaymentStatus']; // PaymentStatus!
      txHash?: string | null; // String
    }
    updatePayroll: { // args
      customDays?: number | null; // Int
      employeeIds?: string[] | null; // [ID!]
      id: string; // ID!
      name?: string | null; // String
      schedule?: NexusGenEnums['Schedule'] | null; // Schedule
    }
    updateUser: { // args
      walletBirthdayHeight?: number | null; // Int
      zcashViewingKey?: string | null; // String
    }
  }
  Query: {
    delegateInvite: { // args
      token: string; // String!
    }
    employee: { // args
      id: string; // ID!
    }
    payments: { // args
      employeeId?: string | null; // ID
      payrollId?: string | null; // ID
    }
    payroll: { // args
      id: string; // ID!
    }
    payrollRun: { // args
      id: string; // ID!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}