/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./../src/context"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  SealedRecordDelete: { // input type
    id: string; // ID!
    version: number; // Int!
  }
  SealedRecordWrite: { // input type
    data: string; // String!
    id: string; // ID!
    version: number; // Int!
  }
  ViewingKeyMessageInput: { // input type
    message: string; // String!
    userId: string; // ID!
  }
}

export interface NexusGenEnums {
  AccessRole: "DELEGATE" | "MEMBER"
  ApprovalDecision: "APPROVE" | "REJECT"
  SpendProposalStatus: "AWAITING_APPROVALS" | "BROADCAST" | "CANCELLED" | "CONFIRMED" | "FAILED" | "SIGNING"
  TreasuryStatus: "ACTIVE" | "DRAFT" | "KEYGEN"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  AccessInvite: { // root type
    id: string; // ID!
    role: NexusGenEnums['AccessRole']; // AccessRole!
  }
  AccessInvitePreview: { // root type
    expiresAt: string; // String!
    ownerUsername: string; // String!
    role: NexusGenEnums['AccessRole']; // AccessRole!
  }
  AccountKey: { // root type
    exists: boolean; // Boolean!
    sealedBy?: string | null; // String
    sealedKey?: string | null; // String
  }
  AuthPayload: { // root type
    token: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Mutation: {};
  Passkey: { // root type
    credentialId: string; // String!
    id: string; // ID!
    prfSalt: string; // String!
    transports: string[]; // [String!]!
    wrappedVaultKey: string; // String!
  }
  ProposalApproval: { // root type
    decision: NexusGenEnums['ApprovalDecision']; // ApprovalDecision!
    id: string; // ID!
  }
  Query: {};
  SealedRecord: { // root type
    data: string; // String!
    id: string; // ID!
    version: number; // Int!
  }
  SpendProposal: { // root type
    error?: string | null; // String
    frostSessionId: string; // String!
    id: string; // ID!
    progress?: string | null; // String
    sealed: string; // String!
    sealedPczt?: string | null; // String
    sealedTxid?: string | null; // String
    signerIds: string[]; // [ID!]!
    status: NexusGenEnums['SpendProposalStatus']; // SpendProposalStatus!
  }
  Treasury: { // root type
    address?: string | null; // String
    birthdayHeight?: number | null; // Int
    changeAddress?: string | null; // String
    description?: string | null; // String
    dkgSessionId?: string | null; // String
    groupPublicKey?: string | null; // String
    id: string; // ID!
    name: string; // String!
    publicKeyPackage?: string | null; // String
    sealedBalance?: string | null; // String
    status: NexusGenEnums['TreasuryStatus']; // TreasuryStatus!
    threshold: number; // Int!
  }
  TreasuryInvite: { // root type
    id: string; // ID!
  }
  TreasuryInvitePreview: { // root type
    expiresAt: string; // String!
    memberCount: number; // Int!
    ownerUsername: string; // String!
    threshold: number; // Int!
    treasuryDescription?: string | null; // String
    treasuryName: string; // String!
  }
  TreasuryMember: { // root type
    groupPublicKey?: string | null; // String
    id: string; // ID!
    identifier?: string | null; // String
  }
  User: { // root type
    commsPublicKey?: string | null; // String
    id: string; // ID!
    name?: string | null; // String
    username: string; // String!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  AccessInvite: { // field return type
    createdAt: string; // String!
    expiresAt: string; // String!
    id: string; // ID!
    role: NexusGenEnums['AccessRole']; // AccessRole!
    token: string; // String!
  }
  AccessInvitePreview: { // field return type
    expiresAt: string; // String!
    ownerUsername: string; // String!
    role: NexusGenEnums['AccessRole']; // AccessRole!
  }
  AccountKey: { // field return type
    exists: boolean; // Boolean!
    sealedBy: string | null; // String
    sealedKey: string | null; // String
  }
  AuthPayload: { // field return type
    token: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Mutation: { // field return type
    acceptAccessInvite: NexusGenRootTypes['AuthPayload']; // AuthPayload!
    acceptTreasuryInvite: NexusGenRootTypes['AuthPayload']; // AuthPayload!
    approveSpendProposal: NexusGenRootTypes['SpendProposal']; // SpendProposal!
    cancelSpendProposal: NexusGenRootTypes['SpendProposal']; // SpendProposal!
    changePassword: NexusGenRootTypes['AuthPayload']; // AuthPayload!
    createAccessInvite: NexusGenRootTypes['AccessInvite']; // AccessInvite!
    createAccountKey: NexusGenRootTypes['AccountKey']; // AccountKey!
    createSpendProposal: NexusGenRootTypes['SpendProposal']; // SpendProposal!
    createTreasury: NexusGenRootTypes['Treasury']; // Treasury!
    createTreasuryInvite: NexusGenRootTypes['TreasuryInvite']; // TreasuryInvite!
    deleteAccount: boolean; // Boolean!
    deleteTreasury: boolean; // Boolean!
    finalizeTreasury: NexusGenRootTypes['Treasury']; // Treasury!
    login: NexusGenRootTypes['AuthPayload']; // AuthPayload!
    markProposalBroadcast: NexusGenRootTypes['SpendProposal']; // SpendProposal!
    markProposalConfirmed: NexusGenRootTypes['SpendProposal']; // SpendProposal!
    markProposalSigned: NexusGenRootTypes['SpendProposal']; // SpendProposal!
    register: NexusGenRootTypes['AuthPayload']; // AuthPayload!
    registerPasskey: NexusGenRootTypes['Passkey']; // Passkey!
    rejectSpendProposal: NexusGenRootTypes['SpendProposal']; // SpendProposal!
    removeAccountMember: NexusGenRootTypes['User']; // User!
    removePasskey: NexusGenRootTypes['Passkey']; // Passkey!
    removeTreasuryMember: NexusGenRootTypes['TreasuryMember']; // TreasuryMember!
    reportProposalProblem: NexusGenRootTypes['SpendProposal']; // SpendProposal!
    reportProposalProgress: NexusGenRootTypes['SpendProposal']; // SpendProposal!
    reportTreasuryBalance: NexusGenRootTypes['Treasury']; // Treasury!
    resetTreasuryKeygen: NexusGenRootTypes['Treasury']; // Treasury!
    revokeAccessInvite: NexusGenRootTypes['AccessInvite']; // AccessInvite!
    revokeTreasuryInvite: NexusGenRootTypes['TreasuryInvite']; // TreasuryInvite!
    setMemberAccess: NexusGenRootTypes['User']; // User!
    setProposalSigners: NexusGenRootTypes['SpendProposal']; // SpendProposal!
    shareAccountKey: NexusGenRootTypes['User']; // User!
    shareTreasuryViewingKey: NexusGenRootTypes['Treasury']; // Treasury!
    startTreasuryKeygen: NexusGenRootTypes['Treasury']; // Treasury!
    submitKeygenResult: NexusGenRootTypes['TreasuryMember']; // TreasuryMember!
    treasuryHeartbeat: NexusGenRootTypes['TreasuryMember']; // TreasuryMember!
    updateTreasury: NexusGenRootTypes['Treasury']; // Treasury!
    writeSealedRecords: NexusGenRootTypes['SealedRecord'][]; // [SealedRecord!]!
  }
  Passkey: { // field return type
    createdAt: string; // String!
    credentialId: string; // String!
    id: string; // ID!
    prfSalt: string; // String!
    transports: string[]; // [String!]!
    wrappedVaultKey: string; // String!
  }
  ProposalApproval: { // field return type
    createdAt: string; // String!
    decision: NexusGenEnums['ApprovalDecision']; // ApprovalDecision!
    id: string; // ID!
    signedAt: string | null; // String
    user: NexusGenRootTypes['User']; // User!
  }
  Query: { // field return type
    accessInvite: NexusGenRootTypes['AccessInvitePreview'] | null; // AccessInvitePreview
    accessInvites: NexusGenRootTypes['AccessInvite'][]; // [AccessInvite!]!
    accountKey: NexusGenRootTypes['AccountKey']; // AccountKey!
    accountMembers: NexusGenRootTypes['User'][]; // [User!]!
    me: NexusGenRootTypes['User'] | null; // User
    myPasskeys: NexusGenRootTypes['Passkey'][]; // [Passkey!]!
    sealedRecords: NexusGenRootTypes['SealedRecord'][]; // [SealedRecord!]!
    spendProposal: NexusGenRootTypes['SpendProposal'] | null; // SpendProposal
    spendProposals: NexusGenRootTypes['SpendProposal'][]; // [SpendProposal!]!
    treasury: NexusGenRootTypes['Treasury'] | null; // Treasury
    treasuryInvite: NexusGenRootTypes['TreasuryInvitePreview'] | null; // TreasuryInvitePreview
  }
  SealedRecord: { // field return type
    data: string; // String!
    id: string; // ID!
    version: number; // Int!
  }
  SpendProposal: { // field return type
    approvals: NexusGenRootTypes['ProposalApproval'][]; // [ProposalApproval!]!
    broadcastAt: string | null; // String
    confirmedAt: string | null; // String
    createdAt: string; // String!
    createdBy: NexusGenRootTypes['User']; // User!
    error: string | null; // String
    expiresAt: string; // String!
    frostSessionId: string; // String!
    id: string; // ID!
    myApproval: NexusGenRootTypes['ProposalApproval'] | null; // ProposalApproval
    progress: string | null; // String
    progressAt: string | null; // String
    sealed: string; // String!
    sealedPczt: string | null; // String
    sealedTxid: string | null; // String
    signerIds: string[]; // [ID!]!
    status: NexusGenEnums['SpendProposalStatus']; // SpendProposalStatus!
    threshold: number; // Int!
  }
  Treasury: { // field return type
    address: string | null; // String
    birthdayHeight: number | null; // Int
    changeAddress: string | null; // String
    coordinator: NexusGenRootTypes['User']; // User!
    createdAt: string; // String!
    description: string | null; // String
    dkgSessionId: string | null; // String
    encryptedViewingKey: string | null; // String
    groupPublicKey: string | null; // String
    id: string; // ID!
    invites: NexusGenRootTypes['TreasuryInvite'][]; // [TreasuryInvite!]!
    isCoordinator: boolean; // Boolean!
    keygenStartedAt: string | null; // String
    members: NexusGenRootTypes['TreasuryMember'][]; // [TreasuryMember!]!
    myMembership: NexusGenRootTypes['TreasuryMember'] | null; // TreasuryMember
    name: string; // String!
    publicKeyPackage: string | null; // String
    sealedBalance: string | null; // String
    signerCount: number; // Int!
    status: NexusGenEnums['TreasuryStatus']; // TreasuryStatus!
    threshold: number; // Int!
  }
  TreasuryInvite: { // field return type
    createdAt: string; // String!
    expiresAt: string; // String!
    id: string; // ID!
    token: string; // String!
  }
  TreasuryInvitePreview: { // field return type
    expiresAt: string; // String!
    memberCount: number; // Int!
    ownerUsername: string; // String!
    threshold: number; // Int!
    treasuryDescription: string | null; // String
    treasuryName: string; // String!
  }
  TreasuryMember: { // field return type
    encryptedKeyPackage: string | null; // String
    groupPublicKey: string | null; // String
    hasKeyShare: boolean; // Boolean!
    hasViewingKey: boolean; // Boolean!
    id: string; // ID!
    identifier: string | null; // String
    isCoordinator: boolean; // Boolean!
    joinedAt: string; // String!
    online: boolean; // Boolean!
    ready: boolean; // Boolean!
    user: NexusGenRootTypes['User']; // User!
    viewingKeyMessage: string | null; // String
  }
  User: { // field return type
    canEditPayroll: boolean; // Boolean!
    commsPublicKey: string | null; // String
    createdAt: string; // String!
    hasAccountKey: boolean; // Boolean!
    hasPasskey: boolean; // Boolean!
    hasTreasury: boolean; // Boolean!
    id: string; // ID!
    isAccountOwner: boolean; // Boolean!
    name: string | null; // String
    owner: NexusGenRootTypes['User'] | null; // User
    role: NexusGenEnums['AccessRole'] | null; // AccessRole
    username: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  AccessInvite: { // field return type name
    createdAt: 'String'
    expiresAt: 'String'
    id: 'ID'
    role: 'AccessRole'
    token: 'String'
  }
  AccessInvitePreview: { // field return type name
    expiresAt: 'String'
    ownerUsername: 'String'
    role: 'AccessRole'
  }
  AccountKey: { // field return type name
    exists: 'Boolean'
    sealedBy: 'String'
    sealedKey: 'String'
  }
  AuthPayload: { // field return type name
    token: 'String'
    user: 'User'
  }
  Mutation: { // field return type name
    acceptAccessInvite: 'AuthPayload'
    acceptTreasuryInvite: 'AuthPayload'
    approveSpendProposal: 'SpendProposal'
    cancelSpendProposal: 'SpendProposal'
    changePassword: 'AuthPayload'
    createAccessInvite: 'AccessInvite'
    createAccountKey: 'AccountKey'
    createSpendProposal: 'SpendProposal'
    createTreasury: 'Treasury'
    createTreasuryInvite: 'TreasuryInvite'
    deleteAccount: 'Boolean'
    deleteTreasury: 'Boolean'
    finalizeTreasury: 'Treasury'
    login: 'AuthPayload'
    markProposalBroadcast: 'SpendProposal'
    markProposalConfirmed: 'SpendProposal'
    markProposalSigned: 'SpendProposal'
    register: 'AuthPayload'
    registerPasskey: 'Passkey'
    rejectSpendProposal: 'SpendProposal'
    removeAccountMember: 'User'
    removePasskey: 'Passkey'
    removeTreasuryMember: 'TreasuryMember'
    reportProposalProblem: 'SpendProposal'
    reportProposalProgress: 'SpendProposal'
    reportTreasuryBalance: 'Treasury'
    resetTreasuryKeygen: 'Treasury'
    revokeAccessInvite: 'AccessInvite'
    revokeTreasuryInvite: 'TreasuryInvite'
    setMemberAccess: 'User'
    setProposalSigners: 'SpendProposal'
    shareAccountKey: 'User'
    shareTreasuryViewingKey: 'Treasury'
    startTreasuryKeygen: 'Treasury'
    submitKeygenResult: 'TreasuryMember'
    treasuryHeartbeat: 'TreasuryMember'
    updateTreasury: 'Treasury'
    writeSealedRecords: 'SealedRecord'
  }
  Passkey: { // field return type name
    createdAt: 'String'
    credentialId: 'String'
    id: 'ID'
    prfSalt: 'String'
    transports: 'String'
    wrappedVaultKey: 'String'
  }
  ProposalApproval: { // field return type name
    createdAt: 'String'
    decision: 'ApprovalDecision'
    id: 'ID'
    signedAt: 'String'
    user: 'User'
  }
  Query: { // field return type name
    accessInvite: 'AccessInvitePreview'
    accessInvites: 'AccessInvite'
    accountKey: 'AccountKey'
    accountMembers: 'User'
    me: 'User'
    myPasskeys: 'Passkey'
    sealedRecords: 'SealedRecord'
    spendProposal: 'SpendProposal'
    spendProposals: 'SpendProposal'
    treasury: 'Treasury'
    treasuryInvite: 'TreasuryInvitePreview'
  }
  SealedRecord: { // field return type name
    data: 'String'
    id: 'ID'
    version: 'Int'
  }
  SpendProposal: { // field return type name
    approvals: 'ProposalApproval'
    broadcastAt: 'String'
    confirmedAt: 'String'
    createdAt: 'String'
    createdBy: 'User'
    error: 'String'
    expiresAt: 'String'
    frostSessionId: 'String'
    id: 'ID'
    myApproval: 'ProposalApproval'
    progress: 'String'
    progressAt: 'String'
    sealed: 'String'
    sealedPczt: 'String'
    sealedTxid: 'String'
    signerIds: 'ID'
    status: 'SpendProposalStatus'
    threshold: 'Int'
  }
  Treasury: { // field return type name
    address: 'String'
    birthdayHeight: 'Int'
    changeAddress: 'String'
    coordinator: 'User'
    createdAt: 'String'
    description: 'String'
    dkgSessionId: 'String'
    encryptedViewingKey: 'String'
    groupPublicKey: 'String'
    id: 'ID'
    invites: 'TreasuryInvite'
    isCoordinator: 'Boolean'
    keygenStartedAt: 'String'
    members: 'TreasuryMember'
    myMembership: 'TreasuryMember'
    name: 'String'
    publicKeyPackage: 'String'
    sealedBalance: 'String'
    signerCount: 'Int'
    status: 'TreasuryStatus'
    threshold: 'Int'
  }
  TreasuryInvite: { // field return type name
    createdAt: 'String'
    expiresAt: 'String'
    id: 'ID'
    token: 'String'
  }
  TreasuryInvitePreview: { // field return type name
    expiresAt: 'String'
    memberCount: 'Int'
    ownerUsername: 'String'
    threshold: 'Int'
    treasuryDescription: 'String'
    treasuryName: 'String'
  }
  TreasuryMember: { // field return type name
    encryptedKeyPackage: 'String'
    groupPublicKey: 'String'
    hasKeyShare: 'Boolean'
    hasViewingKey: 'Boolean'
    id: 'ID'
    identifier: 'String'
    isCoordinator: 'Boolean'
    joinedAt: 'String'
    online: 'Boolean'
    ready: 'Boolean'
    user: 'User'
    viewingKeyMessage: 'String'
  }
  User: { // field return type name
    canEditPayroll: 'Boolean'
    commsPublicKey: 'String'
    createdAt: 'String'
    hasAccountKey: 'Boolean'
    hasPasskey: 'Boolean'
    hasTreasury: 'Boolean'
    id: 'ID'
    isAccountOwner: 'Boolean'
    name: 'String'
    owner: 'User'
    role: 'AccessRole'
    username: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    acceptAccessInvite: { // args
      name: string; // String!
      password: string; // String!
      token: string; // String!
      username: string; // String!
    }
    acceptTreasuryInvite: { // args
      name?: string | null; // String
      password?: string | null; // String
      token: string; // String!
      username?: string | null; // String
    }
    approveSpendProposal: { // args
      id: string; // ID!
    }
    cancelSpendProposal: { // args
      id: string; // ID!
      reason?: string | null; // String
    }
    changePassword: { // args
      currentPassword: string; // String!
      newPassword: string; // String!
    }
    createAccessInvite: { // args
      role?: NexusGenEnums['AccessRole'] | null; // AccessRole
    }
    createAccountKey: { // args
      sealedKey: string; // String!
    }
    createSpendProposal: { // args
      frostSessionId: string; // String!
      id: string; // ID!
      sealed: string; // String!
      sealedPczt: string; // String!
    }
    createTreasury: { // args
      description?: string | null; // String
      name: string; // String!
    }
    deleteAccount: { // args
      treasuryEmpty?: boolean | null; // Boolean
    }
    finalizeTreasury: { // args
      address: string; // String!
      birthdayHeight: number; // Int!
      changeAddress: string; // String!
      encryptedViewingKey: string; // String!
      viewingKeyMessages: NexusGenInputs['ViewingKeyMessageInput'][]; // [ViewingKeyMessageInput!]!
    }
    login: { // args
      password: string; // String!
      username: string; // String!
    }
    markProposalBroadcast: { // args
      id: string; // ID!
      sealedTxid: string; // String!
    }
    markProposalConfirmed: { // args
      id: string; // ID!
    }
    markProposalSigned: { // args
      id: string; // ID!
    }
    register: { // args
      password: string; // String!
      username: string; // String!
    }
    registerPasskey: { // args
      commsPublicKey: string; // String!
      credentialId: string; // String!
      prfSalt: string; // String!
      transports?: string[] | null; // [String!]
      wrappedVaultKey: string; // String!
    }
    rejectSpendProposal: { // args
      id: string; // ID!
    }
    removeAccountMember: { // args
      userId: string; // ID!
    }
    removePasskey: { // args
      id: string; // ID!
    }
    removeTreasuryMember: { // args
      id: string; // ID!
    }
    reportProposalProblem: { // args
      id: string; // ID!
      problem?: string | null; // String
    }
    reportProposalProgress: { // args
      id: string; // ID!
      progress?: string | null; // String
    }
    reportTreasuryBalance: { // args
      sealedBalance: string; // String!
    }
    revokeAccessInvite: { // args
      id: string; // ID!
    }
    revokeTreasuryInvite: { // args
      id: string; // ID!
    }
    setMemberAccess: { // args
      role: NexusGenEnums['AccessRole']; // AccessRole!
      userId: string; // ID!
    }
    setProposalSigners: { // args
      id: string; // ID!
      userIds: string[]; // [ID!]!
    }
    shareAccountKey: { // args
      sealedKey: string; // String!
      userId: string; // ID!
    }
    shareTreasuryViewingKey: { // args
      viewingKeyMessages: NexusGenInputs['ViewingKeyMessageInput'][]; // [ViewingKeyMessageInput!]!
    }
    startTreasuryKeygen: { // args
      dkgSessionId: string; // String!
    }
    submitKeygenResult: { // args
      dkgSessionId: string; // String!
      encryptedKeyPackage: string; // String!
      groupPublicKey: string; // String!
      identifier: string; // String!
      publicKeyPackage: string; // String!
    }
    treasuryHeartbeat: { // args
      ready: boolean; // Boolean!
    }
    updateTreasury: { // args
      description?: string | null; // String
      name?: string | null; // String
      threshold?: number | null; // Int
    }
    writeSealedRecords: { // args
      deletes?: NexusGenInputs['SealedRecordDelete'][] | null; // [SealedRecordDelete!]
      writes: NexusGenInputs['SealedRecordWrite'][]; // [SealedRecordWrite!]!
    }
  }
  Query: {
    accessInvite: { // args
      token: string; // String!
    }
    spendProposal: { // args
      id: string; // ID!
    }
    spendProposals: { // args
      open?: boolean | null; // Boolean
    }
    treasuryInvite: { // args
      token: string; // String!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}