/* eslint-disable */
import * as types from './graphql';
import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "query MeSidebar {\n  me {\n    id\n    email\n  }\n  zecBalance {\n    available\n  }\n}": typeof types.MeSidebarDocument,
    "query PayrollsForDisburse {\n  payrolls {\n    id\n    name\n    schedule\n    customDays\n    employees {\n      employeeId\n      employee {\n        id\n        name\n        walletAddress\n        salaryAmount\n      }\n    }\n  }\n}\n\nmutation StartPayrollRun($payrollId: ID!) {\n  startPayrollRun(payrollId: $payrollId) {\n    id\n    status\n    zecPriceUsd\n    payments {\n      id\n      amountUsd\n      amountZec\n      memo\n      status\n      employee {\n        name\n        walletAddress\n      }\n    }\n  }\n}\n\nmutation UpdatePaymentStatus($paymentId: ID!, $status: PaymentStatus!, $txHash: String) {\n  updatePaymentStatus(paymentId: $paymentId, status: $status, txHash: $txHash) {\n    id\n    status\n  }\n}\n\nmutation CompletePayrollRun($runId: ID!) {\n  completePayrollRun(runId: $runId) {\n    id\n    status\n  }\n}": typeof types.PayrollsForDisburseDocument,
    "fragment EmployeeFields on Employee {\n  id\n  name\n  walletAddress\n  salaryAmount\n  salaryCurrency\n}\n\nfragment PayrollFields on Payroll {\n  id\n  name\n  schedule\n  customDays\n  employees {\n    employeeId\n    employee {\n      ...EmployeeFields\n    }\n  }\n}\n\nfragment PaymentFields on Payment {\n  id\n  amountUsd\n  amountZec\n  status\n  txHash\n  createdAt\n  employee {\n    name\n    walletAddress\n  }\n  payroll {\n    name\n  }\n}\n\nfragment PayrollRunFields on PayrollRun {\n  id\n  status\n  zecPriceUsd\n  createdAt\n  completedAt\n  payroll {\n    name\n  }\n  payments {\n    ...PaymentFields\n  }\n}": typeof types.EmployeeFieldsFragmentDoc,
    "query MeLayout {\n  me {\n    id\n    zcashViewingKey\n    walletBirthdayHeight\n  }\n}": typeof types.MeLayoutDocument,
    "query DashboardStats {\n  dashboardStats {\n    zecSpentByMonth {\n      month\n      amount\n    }\n  }\n  payrolls {\n    id\n    name\n    schedule\n    customDays\n    employees {\n      employeeId\n      employee {\n        id\n        name\n        salaryAmount\n      }\n    }\n    runs {\n      id\n      status\n      createdAt\n    }\n  }\n}": typeof types.DashboardStatsDocument,
    "query Employees {\n  employees {\n    id\n    name\n    title\n    walletAddress\n    walletVerified\n    salaryAmount\n    salaryCurrency\n  }\n}\n\nmutation CreateEmployee($name: String!, $title: String, $walletAddress: String!, $salaryAmount: Float!, $salaryCurrency: SalaryCurrency) {\n  createEmployee(\n    name: $name\n    title: $title\n    walletAddress: $walletAddress\n    salaryAmount: $salaryAmount\n    salaryCurrency: $salaryCurrency\n  ) {\n    id\n    name\n    title\n    walletAddress\n    walletVerified\n    salaryAmount\n    salaryCurrency\n  }\n}\n\nmutation UpdateEmployee($id: ID!, $name: String, $title: String, $walletAddress: String, $salaryAmount: Float, $salaryCurrency: SalaryCurrency) {\n  updateEmployee(\n    id: $id\n    name: $name\n    title: $title\n    walletAddress: $walletAddress\n    salaryAmount: $salaryAmount\n    salaryCurrency: $salaryCurrency\n  ) {\n    id\n    name\n    title\n    walletAddress\n    walletVerified\n    salaryAmount\n    salaryCurrency\n  }\n}\n\nmutation DeleteEmployee($id: ID!) {\n  deleteEmployee(id: $id) {\n    id\n  }\n}\n\nmutation ImportEmployeesCsv($csvContent: String!) {\n  importEmployeesCsv(csvContent: $csvContent) {\n    id\n    name\n    title\n    walletAddress\n    walletVerified\n    salaryAmount\n    salaryCurrency\n  }\n}": typeof types.EmployeesDocument,
    "mutation RegisterUser($email: String!, $tribeUserId: String!, $zcashViewingKey: String) {\n  registerUser(\n    email: $email\n    tribeUserId: $tribeUserId\n    zcashViewingKey: $zcashViewingKey\n  ) {\n    id\n    email\n  }\n}\n\nquery Me {\n  me {\n    id\n    email\n    zcashViewingKey\n  }\n}": typeof types.RegisterUserDocument,
    "query Payrolls {\n  payrolls {\n    id\n    name\n    schedule\n    customDays\n    employees {\n      employeeId\n      employee {\n        id\n        name\n        salaryAmount\n      }\n    }\n    runs {\n      id\n      status\n      createdAt\n    }\n  }\n}\n\nquery Payroll($id: ID!) {\n  payroll(id: $id) {\n    id\n    name\n    schedule\n    customDays\n    employees {\n      employeeId\n      employee {\n        id\n        name\n        walletAddress\n        salaryAmount\n      }\n    }\n    runs {\n      id\n      status\n      createdAt\n    }\n  }\n}\n\nquery AllEmployees {\n  employees {\n    id\n    name\n    salaryAmount\n  }\n}\n\nmutation CreatePayroll($name: String!, $schedule: Schedule!, $customDays: Int, $employeeIds: [ID!]!) {\n  createPayroll(\n    name: $name\n    schedule: $schedule\n    customDays: $customDays\n    employeeIds: $employeeIds\n  ) {\n    id\n  }\n}\n\nmutation UpdatePayroll($id: ID!, $name: String, $schedule: Schedule, $customDays: Int, $employeeIds: [ID!]) {\n  updatePayroll(\n    id: $id\n    name: $name\n    schedule: $schedule\n    customDays: $customDays\n    employeeIds: $employeeIds\n  ) {\n    id\n  }\n}\n\nmutation DeletePayroll($id: ID!) {\n  deletePayroll(id: $id) {\n    id\n  }\n}\n\nquery ZecBalance {\n  zecBalance {\n    available\n  }\n}": typeof types.PayrollsDocument,
    "query MeSettings {\n  me {\n    id\n    email\n    zcashViewingKey\n    walletBirthdayHeight\n  }\n}\n\nmutation UpdateUser($zcashViewingKey: String, $walletBirthdayHeight: Int) {\n  updateUser(\n    zcashViewingKey: $zcashViewingKey\n    walletBirthdayHeight: $walletBirthdayHeight\n  ) {\n    id\n    zcashViewingKey\n    walletBirthdayHeight\n  }\n}": typeof types.MeSettingsDocument,
    "query Payments {\n  payments {\n    id\n    amountUsd\n    amountZec\n    memo\n    status\n    txHash\n    createdAt\n    employee {\n      name\n    }\n    payroll {\n      name\n    }\n  }\n}": typeof types.PaymentsDocument,
};
const documents: Documents = {
    "query MeSidebar {\n  me {\n    id\n    email\n  }\n  zecBalance {\n    available\n  }\n}": types.MeSidebarDocument,
    "query PayrollsForDisburse {\n  payrolls {\n    id\n    name\n    schedule\n    customDays\n    employees {\n      employeeId\n      employee {\n        id\n        name\n        walletAddress\n        salaryAmount\n      }\n    }\n  }\n}\n\nmutation StartPayrollRun($payrollId: ID!) {\n  startPayrollRun(payrollId: $payrollId) {\n    id\n    status\n    zecPriceUsd\n    payments {\n      id\n      amountUsd\n      amountZec\n      memo\n      status\n      employee {\n        name\n        walletAddress\n      }\n    }\n  }\n}\n\nmutation UpdatePaymentStatus($paymentId: ID!, $status: PaymentStatus!, $txHash: String) {\n  updatePaymentStatus(paymentId: $paymentId, status: $status, txHash: $txHash) {\n    id\n    status\n  }\n}\n\nmutation CompletePayrollRun($runId: ID!) {\n  completePayrollRun(runId: $runId) {\n    id\n    status\n  }\n}": types.PayrollsForDisburseDocument,
    "fragment EmployeeFields on Employee {\n  id\n  name\n  walletAddress\n  salaryAmount\n  salaryCurrency\n}\n\nfragment PayrollFields on Payroll {\n  id\n  name\n  schedule\n  customDays\n  employees {\n    employeeId\n    employee {\n      ...EmployeeFields\n    }\n  }\n}\n\nfragment PaymentFields on Payment {\n  id\n  amountUsd\n  amountZec\n  status\n  txHash\n  createdAt\n  employee {\n    name\n    walletAddress\n  }\n  payroll {\n    name\n  }\n}\n\nfragment PayrollRunFields on PayrollRun {\n  id\n  status\n  zecPriceUsd\n  createdAt\n  completedAt\n  payroll {\n    name\n  }\n  payments {\n    ...PaymentFields\n  }\n}": types.EmployeeFieldsFragmentDoc,
    "query MeLayout {\n  me {\n    id\n    zcashViewingKey\n    walletBirthdayHeight\n  }\n}": types.MeLayoutDocument,
    "query DashboardStats {\n  dashboardStats {\n    zecSpentByMonth {\n      month\n      amount\n    }\n  }\n  payrolls {\n    id\n    name\n    schedule\n    customDays\n    employees {\n      employeeId\n      employee {\n        id\n        name\n        salaryAmount\n      }\n    }\n    runs {\n      id\n      status\n      createdAt\n    }\n  }\n}": types.DashboardStatsDocument,
    "query Employees {\n  employees {\n    id\n    name\n    title\n    walletAddress\n    walletVerified\n    salaryAmount\n    salaryCurrency\n  }\n}\n\nmutation CreateEmployee($name: String!, $title: String, $walletAddress: String!, $salaryAmount: Float!, $salaryCurrency: SalaryCurrency) {\n  createEmployee(\n    name: $name\n    title: $title\n    walletAddress: $walletAddress\n    salaryAmount: $salaryAmount\n    salaryCurrency: $salaryCurrency\n  ) {\n    id\n    name\n    title\n    walletAddress\n    walletVerified\n    salaryAmount\n    salaryCurrency\n  }\n}\n\nmutation UpdateEmployee($id: ID!, $name: String, $title: String, $walletAddress: String, $salaryAmount: Float, $salaryCurrency: SalaryCurrency) {\n  updateEmployee(\n    id: $id\n    name: $name\n    title: $title\n    walletAddress: $walletAddress\n    salaryAmount: $salaryAmount\n    salaryCurrency: $salaryCurrency\n  ) {\n    id\n    name\n    title\n    walletAddress\n    walletVerified\n    salaryAmount\n    salaryCurrency\n  }\n}\n\nmutation DeleteEmployee($id: ID!) {\n  deleteEmployee(id: $id) {\n    id\n  }\n}\n\nmutation ImportEmployeesCsv($csvContent: String!) {\n  importEmployeesCsv(csvContent: $csvContent) {\n    id\n    name\n    title\n    walletAddress\n    walletVerified\n    salaryAmount\n    salaryCurrency\n  }\n}": types.EmployeesDocument,
    "mutation RegisterUser($email: String!, $tribeUserId: String!, $zcashViewingKey: String) {\n  registerUser(\n    email: $email\n    tribeUserId: $tribeUserId\n    zcashViewingKey: $zcashViewingKey\n  ) {\n    id\n    email\n  }\n}\n\nquery Me {\n  me {\n    id\n    email\n    zcashViewingKey\n  }\n}": types.RegisterUserDocument,
    "query Payrolls {\n  payrolls {\n    id\n    name\n    schedule\n    customDays\n    employees {\n      employeeId\n      employee {\n        id\n        name\n        salaryAmount\n      }\n    }\n    runs {\n      id\n      status\n      createdAt\n    }\n  }\n}\n\nquery Payroll($id: ID!) {\n  payroll(id: $id) {\n    id\n    name\n    schedule\n    customDays\n    employees {\n      employeeId\n      employee {\n        id\n        name\n        walletAddress\n        salaryAmount\n      }\n    }\n    runs {\n      id\n      status\n      createdAt\n    }\n  }\n}\n\nquery AllEmployees {\n  employees {\n    id\n    name\n    salaryAmount\n  }\n}\n\nmutation CreatePayroll($name: String!, $schedule: Schedule!, $customDays: Int, $employeeIds: [ID!]!) {\n  createPayroll(\n    name: $name\n    schedule: $schedule\n    customDays: $customDays\n    employeeIds: $employeeIds\n  ) {\n    id\n  }\n}\n\nmutation UpdatePayroll($id: ID!, $name: String, $schedule: Schedule, $customDays: Int, $employeeIds: [ID!]) {\n  updatePayroll(\n    id: $id\n    name: $name\n    schedule: $schedule\n    customDays: $customDays\n    employeeIds: $employeeIds\n  ) {\n    id\n  }\n}\n\nmutation DeletePayroll($id: ID!) {\n  deletePayroll(id: $id) {\n    id\n  }\n}\n\nquery ZecBalance {\n  zecBalance {\n    available\n  }\n}": types.PayrollsDocument,
    "query MeSettings {\n  me {\n    id\n    email\n    zcashViewingKey\n    walletBirthdayHeight\n  }\n}\n\nmutation UpdateUser($zcashViewingKey: String, $walletBirthdayHeight: Int) {\n  updateUser(\n    zcashViewingKey: $zcashViewingKey\n    walletBirthdayHeight: $walletBirthdayHeight\n  ) {\n    id\n    zcashViewingKey\n    walletBirthdayHeight\n  }\n}": types.MeSettingsDocument,
    "query Payments {\n  payments {\n    id\n    amountUsd\n    amountZec\n    memo\n    status\n    txHash\n    createdAt\n    employee {\n      name\n    }\n    payroll {\n      name\n    }\n  }\n}": types.PaymentsDocument,
};

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = gql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function gql(source: string): unknown;

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "query MeSidebar {\n  me {\n    id\n    email\n  }\n  zecBalance {\n    available\n  }\n}"): (typeof documents)["query MeSidebar {\n  me {\n    id\n    email\n  }\n  zecBalance {\n    available\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "query PayrollsForDisburse {\n  payrolls {\n    id\n    name\n    schedule\n    customDays\n    employees {\n      employeeId\n      employee {\n        id\n        name\n        walletAddress\n        salaryAmount\n      }\n    }\n  }\n}\n\nmutation StartPayrollRun($payrollId: ID!) {\n  startPayrollRun(payrollId: $payrollId) {\n    id\n    status\n    zecPriceUsd\n    payments {\n      id\n      amountUsd\n      amountZec\n      memo\n      status\n      employee {\n        name\n        walletAddress\n      }\n    }\n  }\n}\n\nmutation UpdatePaymentStatus($paymentId: ID!, $status: PaymentStatus!, $txHash: String) {\n  updatePaymentStatus(paymentId: $paymentId, status: $status, txHash: $txHash) {\n    id\n    status\n  }\n}\n\nmutation CompletePayrollRun($runId: ID!) {\n  completePayrollRun(runId: $runId) {\n    id\n    status\n  }\n}"): (typeof documents)["query PayrollsForDisburse {\n  payrolls {\n    id\n    name\n    schedule\n    customDays\n    employees {\n      employeeId\n      employee {\n        id\n        name\n        walletAddress\n        salaryAmount\n      }\n    }\n  }\n}\n\nmutation StartPayrollRun($payrollId: ID!) {\n  startPayrollRun(payrollId: $payrollId) {\n    id\n    status\n    zecPriceUsd\n    payments {\n      id\n      amountUsd\n      amountZec\n      memo\n      status\n      employee {\n        name\n        walletAddress\n      }\n    }\n  }\n}\n\nmutation UpdatePaymentStatus($paymentId: ID!, $status: PaymentStatus!, $txHash: String) {\n  updatePaymentStatus(paymentId: $paymentId, status: $status, txHash: $txHash) {\n    id\n    status\n  }\n}\n\nmutation CompletePayrollRun($runId: ID!) {\n  completePayrollRun(runId: $runId) {\n    id\n    status\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "fragment EmployeeFields on Employee {\n  id\n  name\n  walletAddress\n  salaryAmount\n  salaryCurrency\n}\n\nfragment PayrollFields on Payroll {\n  id\n  name\n  schedule\n  customDays\n  employees {\n    employeeId\n    employee {\n      ...EmployeeFields\n    }\n  }\n}\n\nfragment PaymentFields on Payment {\n  id\n  amountUsd\n  amountZec\n  status\n  txHash\n  createdAt\n  employee {\n    name\n    walletAddress\n  }\n  payroll {\n    name\n  }\n}\n\nfragment PayrollRunFields on PayrollRun {\n  id\n  status\n  zecPriceUsd\n  createdAt\n  completedAt\n  payroll {\n    name\n  }\n  payments {\n    ...PaymentFields\n  }\n}"): (typeof documents)["fragment EmployeeFields on Employee {\n  id\n  name\n  walletAddress\n  salaryAmount\n  salaryCurrency\n}\n\nfragment PayrollFields on Payroll {\n  id\n  name\n  schedule\n  customDays\n  employees {\n    employeeId\n    employee {\n      ...EmployeeFields\n    }\n  }\n}\n\nfragment PaymentFields on Payment {\n  id\n  amountUsd\n  amountZec\n  status\n  txHash\n  createdAt\n  employee {\n    name\n    walletAddress\n  }\n  payroll {\n    name\n  }\n}\n\nfragment PayrollRunFields on PayrollRun {\n  id\n  status\n  zecPriceUsd\n  createdAt\n  completedAt\n  payroll {\n    name\n  }\n  payments {\n    ...PaymentFields\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "query MeLayout {\n  me {\n    id\n    zcashViewingKey\n    walletBirthdayHeight\n  }\n}"): (typeof documents)["query MeLayout {\n  me {\n    id\n    zcashViewingKey\n    walletBirthdayHeight\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "query DashboardStats {\n  dashboardStats {\n    zecSpentByMonth {\n      month\n      amount\n    }\n  }\n  payrolls {\n    id\n    name\n    schedule\n    customDays\n    employees {\n      employeeId\n      employee {\n        id\n        name\n        salaryAmount\n      }\n    }\n    runs {\n      id\n      status\n      createdAt\n    }\n  }\n}"): (typeof documents)["query DashboardStats {\n  dashboardStats {\n    zecSpentByMonth {\n      month\n      amount\n    }\n  }\n  payrolls {\n    id\n    name\n    schedule\n    customDays\n    employees {\n      employeeId\n      employee {\n        id\n        name\n        salaryAmount\n      }\n    }\n    runs {\n      id\n      status\n      createdAt\n    }\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "query Employees {\n  employees {\n    id\n    name\n    title\n    walletAddress\n    walletVerified\n    salaryAmount\n    salaryCurrency\n  }\n}\n\nmutation CreateEmployee($name: String!, $title: String, $walletAddress: String!, $salaryAmount: Float!, $salaryCurrency: SalaryCurrency) {\n  createEmployee(\n    name: $name\n    title: $title\n    walletAddress: $walletAddress\n    salaryAmount: $salaryAmount\n    salaryCurrency: $salaryCurrency\n  ) {\n    id\n    name\n    title\n    walletAddress\n    walletVerified\n    salaryAmount\n    salaryCurrency\n  }\n}\n\nmutation UpdateEmployee($id: ID!, $name: String, $title: String, $walletAddress: String, $salaryAmount: Float, $salaryCurrency: SalaryCurrency) {\n  updateEmployee(\n    id: $id\n    name: $name\n    title: $title\n    walletAddress: $walletAddress\n    salaryAmount: $salaryAmount\n    salaryCurrency: $salaryCurrency\n  ) {\n    id\n    name\n    title\n    walletAddress\n    walletVerified\n    salaryAmount\n    salaryCurrency\n  }\n}\n\nmutation DeleteEmployee($id: ID!) {\n  deleteEmployee(id: $id) {\n    id\n  }\n}\n\nmutation ImportEmployeesCsv($csvContent: String!) {\n  importEmployeesCsv(csvContent: $csvContent) {\n    id\n    name\n    title\n    walletAddress\n    walletVerified\n    salaryAmount\n    salaryCurrency\n  }\n}"): (typeof documents)["query Employees {\n  employees {\n    id\n    name\n    title\n    walletAddress\n    walletVerified\n    salaryAmount\n    salaryCurrency\n  }\n}\n\nmutation CreateEmployee($name: String!, $title: String, $walletAddress: String!, $salaryAmount: Float!, $salaryCurrency: SalaryCurrency) {\n  createEmployee(\n    name: $name\n    title: $title\n    walletAddress: $walletAddress\n    salaryAmount: $salaryAmount\n    salaryCurrency: $salaryCurrency\n  ) {\n    id\n    name\n    title\n    walletAddress\n    walletVerified\n    salaryAmount\n    salaryCurrency\n  }\n}\n\nmutation UpdateEmployee($id: ID!, $name: String, $title: String, $walletAddress: String, $salaryAmount: Float, $salaryCurrency: SalaryCurrency) {\n  updateEmployee(\n    id: $id\n    name: $name\n    title: $title\n    walletAddress: $walletAddress\n    salaryAmount: $salaryAmount\n    salaryCurrency: $salaryCurrency\n  ) {\n    id\n    name\n    title\n    walletAddress\n    walletVerified\n    salaryAmount\n    salaryCurrency\n  }\n}\n\nmutation DeleteEmployee($id: ID!) {\n  deleteEmployee(id: $id) {\n    id\n  }\n}\n\nmutation ImportEmployeesCsv($csvContent: String!) {\n  importEmployeesCsv(csvContent: $csvContent) {\n    id\n    name\n    title\n    walletAddress\n    walletVerified\n    salaryAmount\n    salaryCurrency\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "mutation RegisterUser($email: String!, $tribeUserId: String!, $zcashViewingKey: String) {\n  registerUser(\n    email: $email\n    tribeUserId: $tribeUserId\n    zcashViewingKey: $zcashViewingKey\n  ) {\n    id\n    email\n  }\n}\n\nquery Me {\n  me {\n    id\n    email\n    zcashViewingKey\n  }\n}"): (typeof documents)["mutation RegisterUser($email: String!, $tribeUserId: String!, $zcashViewingKey: String) {\n  registerUser(\n    email: $email\n    tribeUserId: $tribeUserId\n    zcashViewingKey: $zcashViewingKey\n  ) {\n    id\n    email\n  }\n}\n\nquery Me {\n  me {\n    id\n    email\n    zcashViewingKey\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "query Payrolls {\n  payrolls {\n    id\n    name\n    schedule\n    customDays\n    employees {\n      employeeId\n      employee {\n        id\n        name\n        salaryAmount\n      }\n    }\n    runs {\n      id\n      status\n      createdAt\n    }\n  }\n}\n\nquery Payroll($id: ID!) {\n  payroll(id: $id) {\n    id\n    name\n    schedule\n    customDays\n    employees {\n      employeeId\n      employee {\n        id\n        name\n        walletAddress\n        salaryAmount\n      }\n    }\n    runs {\n      id\n      status\n      createdAt\n    }\n  }\n}\n\nquery AllEmployees {\n  employees {\n    id\n    name\n    salaryAmount\n  }\n}\n\nmutation CreatePayroll($name: String!, $schedule: Schedule!, $customDays: Int, $employeeIds: [ID!]!) {\n  createPayroll(\n    name: $name\n    schedule: $schedule\n    customDays: $customDays\n    employeeIds: $employeeIds\n  ) {\n    id\n  }\n}\n\nmutation UpdatePayroll($id: ID!, $name: String, $schedule: Schedule, $customDays: Int, $employeeIds: [ID!]) {\n  updatePayroll(\n    id: $id\n    name: $name\n    schedule: $schedule\n    customDays: $customDays\n    employeeIds: $employeeIds\n  ) {\n    id\n  }\n}\n\nmutation DeletePayroll($id: ID!) {\n  deletePayroll(id: $id) {\n    id\n  }\n}\n\nquery ZecBalance {\n  zecBalance {\n    available\n  }\n}"): (typeof documents)["query Payrolls {\n  payrolls {\n    id\n    name\n    schedule\n    customDays\n    employees {\n      employeeId\n      employee {\n        id\n        name\n        salaryAmount\n      }\n    }\n    runs {\n      id\n      status\n      createdAt\n    }\n  }\n}\n\nquery Payroll($id: ID!) {\n  payroll(id: $id) {\n    id\n    name\n    schedule\n    customDays\n    employees {\n      employeeId\n      employee {\n        id\n        name\n        walletAddress\n        salaryAmount\n      }\n    }\n    runs {\n      id\n      status\n      createdAt\n    }\n  }\n}\n\nquery AllEmployees {\n  employees {\n    id\n    name\n    salaryAmount\n  }\n}\n\nmutation CreatePayroll($name: String!, $schedule: Schedule!, $customDays: Int, $employeeIds: [ID!]!) {\n  createPayroll(\n    name: $name\n    schedule: $schedule\n    customDays: $customDays\n    employeeIds: $employeeIds\n  ) {\n    id\n  }\n}\n\nmutation UpdatePayroll($id: ID!, $name: String, $schedule: Schedule, $customDays: Int, $employeeIds: [ID!]) {\n  updatePayroll(\n    id: $id\n    name: $name\n    schedule: $schedule\n    customDays: $customDays\n    employeeIds: $employeeIds\n  ) {\n    id\n  }\n}\n\nmutation DeletePayroll($id: ID!) {\n  deletePayroll(id: $id) {\n    id\n  }\n}\n\nquery ZecBalance {\n  zecBalance {\n    available\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "query MeSettings {\n  me {\n    id\n    email\n    zcashViewingKey\n    walletBirthdayHeight\n  }\n}\n\nmutation UpdateUser($zcashViewingKey: String, $walletBirthdayHeight: Int) {\n  updateUser(\n    zcashViewingKey: $zcashViewingKey\n    walletBirthdayHeight: $walletBirthdayHeight\n  ) {\n    id\n    zcashViewingKey\n    walletBirthdayHeight\n  }\n}"): (typeof documents)["query MeSettings {\n  me {\n    id\n    email\n    zcashViewingKey\n    walletBirthdayHeight\n  }\n}\n\nmutation UpdateUser($zcashViewingKey: String, $walletBirthdayHeight: Int) {\n  updateUser(\n    zcashViewingKey: $zcashViewingKey\n    walletBirthdayHeight: $walletBirthdayHeight\n  ) {\n    id\n    zcashViewingKey\n    walletBirthdayHeight\n  }\n}"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "query Payments {\n  payments {\n    id\n    amountUsd\n    amountZec\n    memo\n    status\n    txHash\n    createdAt\n    employee {\n      name\n    }\n    payroll {\n      name\n    }\n  }\n}"): (typeof documents)["query Payments {\n  payments {\n    id\n    amountUsd\n    amountZec\n    memo\n    status\n    txHash\n    createdAt\n    employee {\n      name\n    }\n    payroll {\n      name\n    }\n  }\n}"];

export function gql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;