mutation Login($username: String!, $password: String!) {
  login(username: $username, password: $password) {
    token
    user {
      id
      username
    }
  }
}

mutation Register($username: String!, $password: String!) {
  register(username: $username, password: $password) {
    token
    user {
      id
      username
    }
  }
}

query Me {
  me {
    id
    username
    name
  }
}

mutation AcceptAccessInvite(
  $token: String!
  $name: String!
  $username: String!
  $password: String!
) {
  acceptAccessInvite(
    token: $token
    name: $name
    username: $username
    password: $password
  ) {
    token
    user {
      id
      username
    }
  }
}
