fragment EmployeeFields on Employee {
  id
  name
  walletAddress
  salaryAmount
  salaryCurrency
}

fragment PayrollFields on Payroll {
  id
  name
  schedule
  customDays
  employees {
    employeeId
    employee {
      ...EmployeeFields
    }
  }
}

fragment PaymentFields on Payment {
  id
  amountUsd
  amountZec
  status
  txHash
  createdAt
  employee {
    name
    walletAddress
  }
  payroll {
    name
  }
}

fragment PayrollRunFields on PayrollRun {
  id
  status
  zecPriceUsd
  createdAt
  completedAt
  payroll {
    name
  }
  payments {
    ...PaymentFields
  }
}
